name: Build Toolbox Container

on:
  schedule:
    - cron: '*/59 * * * *'
  push:

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        name: [base, unicamp, lkcamp, ic, others]

    steps:

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and push containers
        run: |
          podman build -t "ghcr.io/${{ github.repository }}:${{ matrix.name }}" ./${{ matrix.name }}
          podman push "ghcr.io/${{ github.repository }}:${{ matrix.name }}"
