name: Build toolbx images

on:
  schedule:
    - cron: '30 */6 * * *'
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        name: [base, unicamp, lkcamp, ic, tex, others]

    steps:

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and push containers
        run: |
          podman build -t "ghcr.io/${{ github.repository }}:${{ matrix.name }}" ./${{ matrix.name }}
          podman push "ghcr.io/${{ github.repository }}:${{ matrix.name }}"
