name: Build Toolbox Container

on:
  schedule:
    - cron: '*/59 * * * *'
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and push containers
        strategy:
          matrix:
            name: [base, unicamp, lkcamp, ic, others]
        steps:
          run: |
            podman build -t "ghcr.io/${{ github.repository }}:${{ github.ref_name }}" ./${{ matrix.name }}
            podman push "ghcr.io/${{ github.repository }}:${{ github.ref_name }}"
